// Static data for deployment
export const staticProfile = {
  id: 1,
  name: "Ishat Noor Mahi",
  title: "Statistics - SUST",
  description: "Statistics student at SUST. Connect with me across platforms for code, projects, and creative content.",
  profileImageUrl: "https://avatars.githubusercontent.com/u/71538842?v=4",
  isOnline: true,
};

export const staticSocialLinks = [
  {
    id: 1,
    name: "Facebook",
    url: "https://www.facebook.com/IN.Mahi",
    icon: "fab fa-facebook-f",
    description: "Connect on Facebook",
    gradientFrom: "#1877F2",
    gradientTo: "#166FE5",
    order: 1,
  },
  {
    id: 2,
    name: "Instagram",
    url: "https://www.instagram.com/n_ordinary__kid___/",
    icon: "fab fa-instagram",
    description: "Visual stories & daily life",
    gradientFrom: "#E4405F",
    gradientTo: "#F77737",
    order: 2,
  },
  {
    id: 3,
    name: "GitHub",
    url: "https://github.com/INmahi/",
    icon: "fab fa-github",
    description: "Code repositories & projects",
    gradientFrom: "#24292e",
    gradientTo: "#0d1117",
    order: 3,
  },
  {
    id: 4,
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/mahi01/",
    icon: "fab fa-linkedin-in",
    description: "Professional network",
    gradientFrom: "#0077B5",
    gradientTo: "#005885",
    order: 4,
  },
  {
    id: 5,
    name: "Discord",
    url: "mahi_787",
    icon: "fab fa-discord",
    description: "Code and hangout with me",
    gradientFrom: "#5865F2",
    gradientTo: "#4752C4",
    order: 5,
  },
  {
    id: 6,
    name: "X",
    url: "https://x.com/IshatNoor",
    icon: "fab fa-x-twitter",
    description: "Thoughts & quick updates",
    gradientFrom: "#000000",
    gradientTo: "#14171A",
    order: 6,
  },
];